### ISSUE TITLE
Setting up Azure account

### ISSUE THREAD

**Issue by jbennyhuang** [JBennyHuang/ecosort#8]
1. create new outlook account
2. use the created account to create an Azure account with free trial

paste credentials for both accounts here

**Comment by AnuragVinodh** [comment]
UserName : ecosortapp@outlook.com
Password: Ec0s0rt123#@!

**Comment by AnuragVinodh** [comment]
https://azure.microsoft.com/en-us/pricing/purchase-options/azure-account?icid=azurefreeaccount
azure try for free button
